* using log directory ‘/var/scratch2/tomas/cran/rlibro/check/PvSTATEM.Rcheck’
* using R Under development (unstable) (2025-01-08 r87540)
* using platform: x86_64-pc-linux-gnu
* R was compiled by
    gcc (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)
    GNU Fortran (GCC) 14.2.1 20240912 (Red Hat 14.2.1-3)
* running under: Fedora Linux 40 (MATE-Compiz)
* using session charset: UTF-8
* checking for file ‘PvSTATEM/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘PvSTATEM’ version ‘0.1.2’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘PvSTATEM’ can be installed ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘PvSTATEM-Ex.R’ failed
The error most likely occurred in:

> ### Name: generate_plate_report
> ### Title: Generate a report for a plate.
> ### Aliases: generate_plate_report
> 
> ### ** Examples
> 
> 
> plate_file <- system.file("extdata", "CovidOISExPONTENT_CO_reduced.csv", package = "PvSTATEM")
> # a plate file with reduced number of analytes to speed up the computation
> layout_file <- system.file("extdata", "CovidOISExPONTENT_CO_layout.xlsx", package = "PvSTATEM")
> note <- "This is a test report.\n**Author**: Jane Doe \n**Tester**: John Doe"
> 
> plate <- read_luminex_data(plate_file, layout_file, verbose = FALSE)
> example_dir <- tempdir(check = TRUE) # a temporary directory
> generate_plate_report(plate,
+   output_dir = example_dir,
+   counts_lower_threshold = 40,
+   counts_higher_threshold = 50,
+   additional_notes = note
+ )
Generating report...This will take approximately 30 seconds.
Error in file(con, "w") : cannot open the connection
Calls: generate_plate_report ... <Anonymous> -> <Anonymous> -> write_utf8 -> writeLines -> file
In addition: Warning message:
In file(con, "w") :
  cannot open file 'plate_report_template.knit.md': Read-only file system
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Expected `generate_plate_report(...)` to run without any errors.
  ℹ Actually got a <simpleError> with text:
    cannot open the connection
  ── Failure ('test-generate_report.R:53:3'): Test generate_levey_jennings_report function ──
  Expected `generate_levey_jennings_report(list(plate), output_dir = tmp_dir)` to run without any errors.
  ℹ Actually got a <simpleError> with text:
    cannot open the connection
  ── Failure ('test-generate_report.R:54:3'): Test generate_levey_jennings_report function ──
  Expected `generate_levey_jennings_report(...)` to run without any errors.
  ℹ Actually got a <simpleError> with text:
    cannot open the connection
  
  [ FAIL 7 | WARN 12 | SKIP 9 | PASS 172 ]
  Error: Test failures
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
Status: 2 ERRORs
